### ISSUE TITLE
What's your CUDA version?

### ISSUE THREAD

**Issue by mehameha998** [vchoutas/torch-mesh-isect#1]
Hi @vchoutas , there is a prolem, hope you can help me. 
When I run setup.py, CUDA INC PATH seems lacks, so I mannualy point it to '/usr/lcoal/cuda/samples/common/inc'. it worked. However, a cuda error happened when i try examples/detect_and_plot_collisions.py. The error is:
Error inside sort: radix_sort: failed on 2nd step: invalid argument
Cuda failure src/bvh_cuda_op.cu:877: 'invalid argument'

**Comment by colijian** [comment]
I meet the same problem .

**Comment by mikeburon** [comment]
this seems to come from a thrust::sort function of cuda... i am trying to look into it because this is blocking me :( help

**Comment by nghorbani** [comment]
I have tested the package with cuda 10, and its compatible cudnn 7.5. 
I believe your LD_LIBRARY_PATH environment variable should include the path to these libraries. here is mine for an example:
ROOT_PATH/nvidia/cudnn-7.5-cu10.0/lib64:ROOT_PATH/nvidia/cuda-10.0/extras/CUPTI/lib64:ROOT_PATH/nvidia/cuda-10.0/lib64:ROOT_PATH/nvidia/cuda-10.0
ofcourse ROOT_PATH should be updated to your situation...

**Comment by vchoutas** [comment]
I have tested this with Pytorch 0.4.1 / CUDA 9.2 and Pytorch 1.1 / CUDA 10.
I will make sure to update the README.
@mehameha998  Could you please share the mesh that you use and gives you the problem?

**Comment by colijian** [comment]
@vchoutas I use Pytorch 1.0.1.post2 and cuda 10.0.130. I test the mesh of smpl

**Comment by Vikramank** [comment]
Can I install without CUDA? is there a way to disable the option to use CUDA?

**Comment by RhythmJnh** [comment]
I meet the same problem, when i run smplif-x in the second step optimization, optimize the full model
    Error inside sort: radix_sort: failed on 2nd step: invalid argument11
    Cuda failure src/bvh_cuda_op.cu:877: 'an illegal memory access was encountered'
I use pytorch 1.1.0, cuda10.1 and cudnn7.6, the mesh is smplx

**Comment by geopavlakos** [comment]
Please take a look at the answers [here](https://github.com/vchoutas/smplify-x/issues/3). Other users having the same problem were able to resolve it by following the instructions posted in one of the answers.
