### ISSUE TITLE
RuntimeError: after reduction step 1: cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by AlyanQ** [vchoutas/torch-mesh-isect#30]
```
python smplifyx/main.py --config cfg_files/fit_smpl.yaml --data_folder input --output_folder output --visualize=True --model_folder models --vposer_ckpt vposer_v1_0 --part_segm_fn smplx_parts_segm.pkl --gender male
Processing: input/images/63f28b0b-765a-440f-9aad-f11bcd64dd4c.jpg
Found Trained Model: vposer_v1_0/snapshots/TR00_E096.pt
/home/arash/Desktop/SMPLX/smplify-x/smplifyx/optimizers/lbfgs_ls.py:238: UserWarning: This overload of add_ is deprecated:
        add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
        add_(Tensor other, *, Number alpha) (Triggered internally at  /opt/conda/conda-bld/pytorch_1627336316785/work/torch/csrc/utils/python_arg_parser.cpp:1005.)
  p.data.add_(step_size, update[offset:offset + numel].view_as(p.data))
Camera initialization done after 3.4924
Camera initialization final loss 1970.4176
Stage 000 done after 1.6123 seconds                                                                                                                              
Stage 001 done after 1.2765 seconds                                                                                                                              
Stage:  50%|███████████████████████████████████████████████████████████▌                                                           | 2/4 [00:02<00:02,  1.50s/it]
Orientation:   0%|                                                                                                                         | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "/home/arash/Desktop/SMPLX/smplify-x/smplifyx/fit_single_frame.py", line 444, in fit_single_frame
    use_vposer=use_vposer)
  File "/home/arash/Desktop/SMPLX/smplify-x/smplifyx/fitting.py", line 175, in run_fitting
    loss = optimizer.step(closure)
  File "/home/arash/anaconda3/envs/scratch/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/arash/Desktop/SMPLX/smplify-x/smplifyx/optimizers/lbfgs_ls.py", line 280, in step
    orig_loss = closure()
  File "/home/arash/Desktop/SMPLX/smplify-x/smplifyx/fitting.py", line 253, in fitting_func
    **kwargs)
  File "/home/arash/anaconda3/envs/scratch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/arash/Desktop/SMPLX/smplify-x/smplifyx/fitting.py", line 434, in forward
    collision_idxs = self.search_tree(triangles)
  File "/home/arash/anaconda3/envs/scratch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/arash/anaconda3/envs/scratch/lib/python3.7/site-packages/mesh_intersection-0.1.0-py3.7-linux-x86_64.egg/mesh_intersection/bvh_search_tree.py", line 56, in forward
    return BVHFunction.apply(triangles)
  File "/home/arash/anaconda3/envs/scratch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/arash/anaconda3/envs/scratch/lib/python3.7/site-packages/mesh_intersection-0.1.0-py3.7-linux-x86_64.egg/mesh_intersection/bvh_search_tree.py", line 39, in forward
    max_collisions=BVHFunction.max_collisions)
RuntimeError: after reduction step 1: cudaErrorInvalidDevice: invalid device ordinal
```

I am getting the above error when trying to run smplify-x project using the interpenetration set to True. My CUDA version is 11.3 and torch correctly detects my cuda installation. I have also tried changing the `device = torch.device('cuda:0')` in all places and then compiling mesh_intersection but that doesn't work either. Let me know how I can check what the device bvh is using and how I can change it. Thanks

Edit 1:
I checked my cuda device number (ordinal) just before this line `max_collisions=BVHFunction.max_collisions` where the error was, the cuda current device number is set to 0 which is correct but i am still getting the error

**Comment by aszxnm** [comment]
I meet the same problem.

**Comment by YuliangXiu** [comment]
get this same problem in colab

![image](https://user-images.githubusercontent.com/7944350/152664026-3d19a457-050f-414b-b755-2ed7f99812c3.png)

**Comment by YuliangXiu** [comment]
> get this same problem in colab
> 
> ![image](https://user-images.githubusercontent.com/7944350/152664026-3d19a457-050f-414b-b755-2ed7f99812c3.png)

Okay, I find out the solution, this version can't work on CUDA 11.1, so I changed the CUDA to 11.0, problem solved!

**Comment by xiyichen** [comment]
@YuliangXiu I'm also having an issue installing this package on colab. Is it possible if you can share the commands you used to make it work on colab? Thank you!
